apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: agent-dev
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - dev
  selector:
    matchLabels:
      app: agent
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: agent-prod
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - prod
  selector:
    matchLabels:
      app: agent
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: yolo-dev
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - dev
  selector:
    matchLabels:
      app: yolo
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: yolo-prod
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - prod
  selector:
    matchLabels:
      app: yolo
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
